version: '3.8'
services:
    db:
        container_name: apivendas
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: apivendas
        ports:
            - '5432:5432'
